ADD VALUE LABELS chapter
 01 '01 Animais vivos'                                                                                                            
 02 '02 Carnes e miudezas, comestíveis'                                                                                          
 03 '03 Peixes e crustáceos, moluscos e outros invertebrados aquáticos'                                                         
 04 '04 Leite e lacticíneos, ovos, mel natural,'                                                                                 
 05 '05 Outros produtos de origem animal,'                                                                                        
 06 '06 Plantas vivas e produtos de floricultura'                                                                                 
 07 '07 Produtos hortícolas, plantas raízes e tubérculos, comestíveis'                                                        
 08 '08 Frutas, cascas de citrino e de melões'                                                                                   
 09 '09 Café, chá, mate e especiarias'                                                                                          
 10 '10 Cereais'                                                                                                                  
 11 '11 Produtos da indústria de moagem, malte, amidos e féculas,'                                                              
 12 '12 Sementes e frutos oleaginosos; grãos, sementes e frutos diversos, plantas industriais'                                   
 13 '13 Gomas, resinas e outros sucos e extractos vegetais'                                                                       
 14 '14 Matérias para entrançamento e outros produtos de origem vegetal, n.e.'                                                  
 15 '15 Gorduras e óleos animais ou vegetais,'                                                                                   
 16 '16 Preparação de carnes, peixe, crustáceos ou de moluscos'                                                                
 17 '17 Açucares e produtos de confeitaria'                                                                                      
 18 '18 Cacau e suas preparações'                                                                                               
 19 '19 Preparações a base de cereais, de farinhas, amidos, de leite, produtos de pastelaria'                                   
 20 '20 Preparações de produtos hortícolas, de frutas ou de outras partes de plantas'                                          
 21 '21 Preparações alimentícias diversas'                                                                                     
 22 '22 Bebidas, líquidos alcoólicos e vinagres'                                                                                
 23 '23 Resíduos e desperdícios das indústrias alimentares; alimentos para animais'                                            
 24 '24 Tabaco ou fumo e seus sucedâneos menufacturados'                                                                         
 25 '25 Sal; enxofre; terras e pedras; gesso, cal e cimento'                                                                      
 26 '26 Minérios, escórias e cinzas'                                                                                            
 27 '27 Combustíveis minerais, óleos minerais e produtos da sua destilação;'                                                  
 28 '28 Produtos químicos inorgânicos'                                                                                          
 29 '29 Produtos químicos orgânicos'                                                                                            
 30 '30 Produtos farmacêuticos'                                                                                                  
 31 '31 Adubos e fertilizantes'                                                                                                   
 32 '32 Extractos tanantes e tintorias, taninos e seus derivados'                                                                 
 33 '33 Óleos essenciais de resinóides, produtos de perfumaria, preparações cosméticas'                                      
 34 '34 Sabões, produtos de limpeza, ceras, velas'                                                                               
 35 '35 Matérias albuminóides, produtos a base de amidos, colas'                                                                
 36 '36 Pólvoras e explosivos, artigos de pirotécnia, fósforos'                                                                
 37 '37 Produtos para fotografia e cinematografia'                                                                                
 38 '38 Produtos diversos das indústrias químicas'                                                                              
 39 '39 Plásticos e suas obras'                                                                                                  
 40 '40 Borracha e suas obras'                                                                                                    
 41 '41 Peles, exceptuadas as peles com pelo e couros'                                                                            
 42 '42 Obras de couro, artigos de coreeiro ou de seleiro, artigos de viagem'                                                     
 43 '43 Peles com pelo e suas obras, peles com pelo'                                                                              
 44 '44 Madeira, carvão vegetal e obras de madeira'                                                                              
 45 '45 Cortiça e suas obras'                                                                                                    
 46 '46 Obras de espartaria ou de cestaria'                                                                                       
 47 '47 Pastas de madeira ou de outras matérias fibrosas celulósicas'                                                           
 48 '48 Papel e cartão, obras de pasta de celulose, de papel ou de cartão'                                                      
 49 '49 Livros, jornais, gravuras e outros produtos das indústrias gráficas'                                                    
 50 '50 Seda'                                                                                                                     
 51 '51 Lã, pelos finos ou grosseiros; fios e tecidos de crina'                                                                  
 52 '52 Algodão'                                                                                                                 
 53 '53 Outras fibras têxteis vegetais; fios de papel e tecidos de fios de papel'                                                
 54 '54 Filamentos sintéticos ou artificiais'                                                                                    
 55 '55 Fibras sintéticas ou artificiais descontínuas'                                                                          
 56 '56 Pastas (ouates), feltros e falsos tecidos; fios especiais; cordéis'                                                      
 57 '57 Tapetes e outros revestimentos, para pavimento de matérias têxteis'                                                     
 58 '58 Tecidos especiais; tecidos tufados, rendas; tapeçarias'                                                                  
 59 '59 Tecidos impregnados, recobertos ou estratificados'                                                                        
 60 '60 Tecidos de malha'                                                                                                         
 61 '61 Vestuário e seus acessórios de malha'                                                                                   
 62 '62 Vestuário e seus acessórios excepto de malha'                                                                           
 63 '63 Outros artefactos têxteis confeccionados; sortidos;'                                                                     
 64 '64 Calçado, polainas e artefactos semelhantes, e suas partes'                                                               
 65 '65 Chápeus e artefactos de uso semelhante, e suas partes'                                                                   
 66 '66 Guarda-chuvas, sombrinhas, guarda-sóis, bengalas-assentos, chicotes'                                                     
 67 '67 Penas e penugem preparadas e suas obras; flores artificiais; obras de cabelo'                                             
 68 '68 Obras de pedra, gesso, cimento, amianto, mica ou de matérias semelhantes'                                                
 69 '69 Produtos cerâmicos'                                                                                                      
 70 '70 Vidro e suas obras'                                                                                                       
 71 '71 Pérolas naturais ou cultivadas, pedras preciosas ou semipreciosas metais preciosos'                                      
 72 '72 Ferro fundido, ferro e aço'                                                                                              
 73 '73 Obras de ferro fundido, ferro ou aço'                                                                                    
 74 '74 Cobre e suas obras'                                                                                                       
 75 '75 Níquel e suas obras'                                                                                                     
 76 '76 Alumínio e suas obras'                                                                                                   
 78 '78 Chumbo e suas obras'                                                                                                      
 79 '79 Zinco e suas obras'                                                                                                       
 80 '80 Estanho e suas obras'                                                                                                     
 81 '81 Outros metais comuns; ceramais (cermets); obras dessas matérias'                                                         
 82 '82 Ferramentas, artefactos de cutelaria e talheres, e suas partes'                                                           
 83 '83 Obras diversas de metais comuns'                                                                                          
 84 '84 Máquinas, aparelhos e instrumentos mecânicos e suas partes'                                                             
 85 '85 Máquinas, aparelhos e materiais eléctricos e suas partes'                                                               
 86 '86 Veículos e material para vias ferreas ou semelhantes e suas partes'                                                      
 87 '87 Veículos automóveis, tractores e outros veículos terrestres e suas partes'                                             
 88 '88 Aeronaves e outros aparelhos aéreos ou espaciais, e suas partes'                                                         
 89 '89 Embarcações e estruturas flutuantes'                                                                                    
 90 '90 Instrumentos e aparelhos de óptica, fotocografia ou cinematografia'                                                      
 91 '91 Relógios e aparelhos semelhantes, e suas partes'                                                                         
 92 '92 Instrumentos musicais, suas partes e acessórios'                                                                         
 93 '93 Armas, e munições; duas partes e acessórios'                                                                           
 94 '94 Móveis, mobil. médico-cirúrgico; colchões, almofadas, aparelhos de iluminação'                                      
 95 '95 Brinquedos, jogos, artigos para divertimentos ou para desporto'                                                           
 96 '96 Obras diversas'                                                                                                           
 97 '97 Objectos de arte, de colecção ou antiguidades'                                                                          
 99 '99 Outros Produtos não Especificados'                                                                                       
.
